jenkins:
  systemMessage: "Controlled by Configuration as Codes"
jobs:
  - script: >
      folder('testjob')
  - script: >
      pipelineJob('testjob/default-agents') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                  stage ('deploy') {
                    steps {
                      echo "hello deploy"
                    }
                  }
                  stage ('Automation') {
                    steps {
                      echo "hello Automation"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
